version: '2'
services:
   nginx:
      restart: always
      build: ./nginx/
      ports:
       - "80:80"
      volumes:
       - /www/static
      volumes_from:
       - web
      links:
       - web:web
   web:
      build:
         context: ./web
         args:
            debug: "True"
            secret_key: "&s!n66v-94ajfbo=reonfh*-it_=o9q&yp)fz(*23p0wp(kojd"
      command: /usr/local/bin/gunicorn weather.wsgi:application -b :8000
      expose:
         - "8000"
      volumes:
         - ./web:/app
         - /app/static
         - ./db:/app/db
      environment:
         DJANGO_DEBUG: "True"
         DJANGO_SECRET_KEY: "&s!n66v-94ajfbo=reonfh*-it_=o9q&yp)fz(*23p0wp(kojd"
